---

- name: Guest user is disabled
  rabbitmq_user:
    user: guest
    state: absent

- name: Admin user exists
  rabbitmq_user:
    name: admin
    password: "{{admin_password}}"
    tags: administrator

- name: Unprivileged user exists
  rabbitmq_user:
    user: user
    password: "{{user_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
